def show_average(window_name,mean):
        root_show=tki.Toplevel(window_name)
        root_show.geometry('620x500')
        root_show.title(mean)
        root_show.resizable(False, False)
        root_show.configure(bg=cfon)
        tki.Label(root_show,text=mean,font=('Times',16,'italic')
                         , bg=cfon, fg='black').pack()
        if mean=='Среднее количество прослушиваний по годам':
            text=open(f=average_in_year(file_path, data),encoding='utf-8').readlines()
            text = ''.join(text)
            textline = Text(root_show)
            textline.insert(1.0, text)
            textline.configure(state='disabled')
            textline.pack(side=BOTTOM,padx=30,pady=30)
            scroll = Scrollbar(command=textline.yview)
            scroll.pack(side=LEFT, fill=Y)
            textline.config(yscrollcommand=scroll.set)
        if mean=='Средняя длина трека':
            text=open(f=average_length(file_path, data),encoding='utf-8').readlines()
            text = ''.join(text)
            textline = Text(root_show)
            textline.insert(1.0, text)
            textline.configure(state='disabled')
            textline.pack(side=BOTTOM,padx=30,pady=30)
            scroll = Scrollbar(command=textline.yview)
            scroll.pack(side=LEFT, fill=Y)
            textline.config(yscrollcommand=scroll.set)
        if mean=='Среднее по жанрам':
            text=open(f= average_genre(file_path, data),encoding='utf-8').readlines()
            text = ''.join(text)
            textline = Text(root_show)
            textline.insert(1.0, text)
            textline.configure(state='disabled')
            textline.pack(side=BOTTOM,padx=30,pady=30)
            scroll = Scrollbar(command=textline.yview)
            scroll.pack(side=LEFT, fill=Y)
            textline.config(yscrollcommand=scroll.set)
            
            #это добавить где кнопки для tab
            tki.Label(tab3,text='Среднее ',font=('Times',16,'italic')
                         , bg=cfon, fg='black').place(x=10,y=10)
            tki.Button(tab3,text='Среднее количество прослушиваний по годам',font=('Times',16,'italic')
                             , bg='black', fg='white',command=lambda:show_average(root_rep, 'Среднее количество прослушиваний по годам')).place(x=10,y=50)
            tki.Button(tab3,text='Средняя длина трека',font=('Times',16,'italic')
                             , bg='black', fg='white',command=lambda:show_average(root_rep, 'Средняя длина трека')).place(x=10,y=90)
            tki.Button(tab3,text='Среднее по жанрам',font=('Times',16,'italic')
                             , bg='black', fg='white',command=lambda:show_average(root_rep, 'Среднее по жанрам')).place(x=10,y=130)
